\text{lang=slib(oef/env lang)}
#if defined TARGET_corrdomain
\author{Marie-Claude,David}

\email{mcld@math.u-psud.fr}

#endif
#if defined TARGET_ineqgr2courbes
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_constrtbvar
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_qcmensdef
\author{Marie-Claude,David}

\email{mcld@math.u-psud.fr}

#endif
#if defined TARGET_eqgr1
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectgrimage2
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectvarimage
\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_compar2val
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_ineqgr2
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_quotient2
\author{Marie-Claude, David}

\computeanswer{no}

#endif
#if defined TARGET_affine3
\author{Marie-Claude, David}

\computeanswer{no}

#endif
#if defined TARGET_lectgrantec
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_ineqgr2dtes
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_extremgr
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_sensvartb
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_quotient3
\author{Marie-Claude, David}

\computeanswer{no}

#endif
#if defined TARGET_extremvar1
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectvarantec
\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lecttbantec
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_ineqgr
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_sensvargr
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_quotient1
\author{Marie-Claude, David}

\email{mcld@math.u-psud.fr}

\computeanswer{no}

#endif
#if defined TARGET_lectgrantec2
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_racine
\author{Marie-Claude, David}

\computeanswer{no}

#endif
#if defined TARGET_lecttbimage
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_eqgr2
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectgrimage
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
