\text{lang=slib(oef/env lang)}
#if defined TARGET_compar2val
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_eqgr1
\language{fr}

\author{Bruno, Mifsud;Cyrille,Douriez} ##D'après un exercice de Régine Mangeard##

\email{communaute.mutuwims@laposte.net;cyrille.douriez@ac-amiens.fr}

\format{html}

#endif
#if defined TARGET_signgraph
\language{fr}

\range{-5..5}

\author{Cyrille,Douriez;Bruno,Mifsud}

\email{Cyrille.douriez@ac-amiens.fr;bmifsud@ac-aix-marseille.fr}

\computeanswer{no}

\format{html}

\precision{100}

#endif
#if defined TARGET_sensvar1
#endif
#if defined TARGET_lecttbantec
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectgrantec
\language{fr}

\author{Bruno, Mifsud;Cyrille,Douriez} ## D'après un exercice de Régine Mangeard##

\email{communaute.mutuwims@laposte.net;cyrille.douriez@ac-amiens.fr}

\format{html}

#endif
#if defined TARGET_ineqgr
\language{fr}

\author{Bruno, Mifsud;Cyrille,Douriez} ## A partir d'un exercice de Régine Mangeard##

\email{communaute.mutuwims@laposte.net;cyrille.douriez@ac-amiens.fr}

\format{html}

#endif
#if defined TARGET_eqgr2
\language{fr}

\author{Bruno, Mifsud;Cyrille,Douriez} ##D'après un exercice de Régine Mangeard##

\email{communaute.mutuwims@laposte.net;cyrille.douriez@ac-amiens.fr}

\format{html}

#endif
#if defined TARGET_exploitabvar
\author{Cyrille,Douriez;Bruno,MIFSUD}

\email{cyrille.douriez@ac-amiens.fr;communaute.mutuwims@laposte.net}

\computeanswer{no}

#endif
#if defined TARGET_corrdomain
\author{Marie-Claude,David}

\email{mcld@math.u-psud.fr}

#endif
#if defined TARGET_racine
\author{Marie-Claude, David}

\computeanswer{no}

#endif
#if defined TARGET_qcmensdef
\author{Marie-Claude,David}

\email{mcld@math.u-psud.fr}

#endif
#if defined TARGET_quotient1
\author{Marie-Claude, David}

\email{mcld@math.u-psud.fr}

\computeanswer{no}

#endif
#if defined TARGET_ineqgr2courbes
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_constrtbvar
\language{fr}

\author{Cyrille,Douriez;Bruno,Mifsud}

\email{cyrille.douriez@ac-amiens.fr;bmifsud@ac-aix-marseille.fr}

\format{html}

#endif
#if defined TARGET_lectvarantec
\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_quotient2
\author{Marie-Claude, David}

\computeanswer{no}

#endif
#if defined TARGET_extremgr
\language{fr}

\author{Bruno, Mifsud;Cyrille,Douriez} ##A partir d'un exercice de Régine Mangeard##

\email{communaute.mutuwims@laposte.net;cyrille.douriez@ac-amiens.fr}

\format{html}

#endif
#if defined TARGET_extremvar1
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_ineqgr2dtes
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectvarimage
\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectgrimage2
\language{fr}

\author{Bruno, Mifsud;Cyrille,Douriez} ## D'après un exercice de Régine Mangeard##

\email{communaute.mutuwims@laposte.net;cyrille.douriez@ac-amiens.fr}

\format{html}

#endif
#if defined TARGET_sensvartb
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_quotient3
\author{Marie-Claude, David}

\computeanswer{no}

#endif
#if defined TARGET_ineqgr2
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectgrimage
\language{fr}

\author{Bruno, Mifsud;Cyrille,Douriez} ## D'après un exercice de Régine Mangeard##

\email{communaute.mutuwims@laposte.net;cyrille.douriez@ac-amiens.fr}

\format{html}

#endif
#if defined TARGET_sensvar3
#endif
#if defined TARGET_sensvargr
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_lectgrantec2
\language{fr}

\author{Bruno, Mifsud;Cyrille,Douriez} ## D'après un exercice de Régine Mangeard##

\email{communaute.mutuwims@laposte.net;cyrille.douriez@ac-amiens.fr}

\format{html}

#endif
#if defined TARGET_lecttbimage
\language{fr}

\author{Régine, Mangeard}

\email{regine@mangeard.fr}

\format{html}

#endif
#if defined TARGET_affine3
\author{Marie-Claude, David}

\computeanswer{no}

#endif
#if defined TARGET_sensvar2
#endif
