#if defined TARGET_compar2val
#endif

#if defined TARGET_eqgr1
#endif

#if defined TARGET_signgraph
#endif

#if defined TARGET_sensvar1
#endif

#if defined TARGET_lecttbantec
#endif

#if defined TARGET_lectgrantec
#endif

#if defined TARGET_ineqgr
#endif

#if defined TARGET_eqgr2
#endif

#if defined TARGET_exploitabvar
#endif

#if defined TARGET_corrdomain
#endif

#if defined TARGET_racine
#endif

#if defined TARGET_qcmensdef
#endif

#if defined TARGET_quotient1
#endif

#if defined TARGET_ineqgr2courbes
#endif

#if defined TARGET_constrtbvar
#endif

#if defined TARGET_lectvarantec
#endif

#if defined TARGET_quotient2
#endif

#if defined TARGET_extremgr
#endif

#if defined TARGET_extremvar1
#endif

#if defined TARGET_ineqgr2dtes
#endif

#if defined TARGET_lectvarimage
#endif

#if defined TARGET_sensvartb
#endif

#if defined TARGET_quotient3
#endif

#if defined TARGET_ineqgr2
#endif

#if defined TARGET_lectgrimage || defined TARGET_lectgrimage2
\text{lintervalle=l'intervallo}
\text{definiesur=definita su}
\text{Limagede=L'immagine di}
\text{estegalea=è uguale a}
\text{Paretape=Passo passo}

\text{name_imgalt=rappresentazione grafica}
\text{name_statement1=Nel piano dotato di un sistema di coordinate cartesiane}
\text{name_statement2=abbiamo tracciato la curva che rappresenta una funzione}
\text{name_statement3=Determinare graficamente l'immagine di}
\text{name_statement4=per la funzione}
\text{name_solution1a=Tracciamo la retta di equazione}
\text{name_solution1b=in blu nel grafico}
\text{name_solution2a=Quindi individuiamo il punto di intersezione con la curva}
\text{name_solution2b=croce blu}
\text{name_solution3a=Infine, guardiamo l'ordinata di questo punto}
\text{name_solution3b=trattini verdi}
#endif

#if defined TARGET_sensvar3
#endif

#if defined TARGET_sensvargr
#endif

#if defined TARGET_lectgrantec2
#endif

#if defined TARGET_lecttbimage
#endif

#if defined TARGET_affine3
#endif

#if defined TARGET_sensvar2
#endif

