#if defined TARGET_compar2val
#endif

#if defined TARGET_eqgr1
#endif

#if defined TARGET_signgraph
#endif

#if defined TARGET_sensvar1
#endif

#if defined TARGET_lecttbantec
#endif

#if defined TARGET_eqgr2
#endif

#if defined TARGET_exploitabvar
#endif

#if defined TARGET_corrdomain
#endif

#if defined TARGET_racine
#endif

#if defined TARGET_qcmensdef
#endif

#if defined TARGET_quotient1
#endif

#if defined TARGET_ineqgr2courbes
#endif

#if defined TARGET_constrtbvar
#endif

#if defined TARGET_lectvarantec
#endif

#if defined TARGET_quotient2
#endif

#if defined TARGET_extremgr
#endif

#if defined TARGET_extremvar1
#endif

#if defined TARGET_ineqgr2dtes
#endif

#if defined TARGET_lectvarimage
#endif

#if defined TARGET_sensvartb
#endif

#if defined TARGET_quotient3
#endif

#if defined TARGET_ineqgr2
#endif

#if defined TARGET_lectgrimage || defined TARGET_lectgrimage2 || defined TARGET_lectgrantec || defined TARGET_lectgrantec2 || defined TARGET_ineqgr
\text{lintervalle=l'intervallo}
\text{definiesur=definita su}
\text{Limagede=L'immagine di}
\text{estegalea=è uguale a}
\text{Paretape=Passo passo}

\text{name_imgalt=rappresentazione grafica}
\text{name_statement1=Nel piano dotato di un sistema di coordinate cartesiane}
\text{name_statement2=abbiamo tracciato il grafico di una funzione}
\text{name_statement4=per la funzione}
\text{name_solution1a=Tracciamo la retta di equazione}
\text{name_solution1b=in blu nel grafico}
\text{name_solution2a=Quindi individuiamo il punto di intersezione con il grafico}
\text{name_solution2b=croce blu}
\text{name_solution3a=Infine, guardiamo l'ordinata di questo punto}
\text{name_solution3b=trattini verdi}
#endif

#if defined TARGET_lectgrimage || defined TARGET_lectgrimage2
\text{name_statement3=Determinare graficamente l'immagine di}
#endif

#if defined TARGET_lectgrantec || defined TARGET_lectgrantec2
\text{name_statement3=Determinare graficamente tutte le controimmagini di}
\text{name_instruction=Se ci sono più soluzioni, devono essere separate da una virgola.}
\text{name_statement5=Le controimmagini sono}
\text{Lantecedentde=La controimmagine di}
\text{Lantecedentsde=Le controimmagini di}
\text{est=è}
\text{sont=sono}
\text{et=e}
\text{name_solution1b=in verde sul grafico}
\text{name_solution3a=Infine, osserviamo le ascisse di questi punti}
\text{name_solution3b=Trattini blu}
#endif

#if defined TARGET_ineqgr
\text{name_statement3=Risolvere graficamente la disequazione}
\text{Votrereponse=La tua risposta}
\text{Lensemble=L'insieme delle soluzioni è}
\text{name_solution0=Risolvi graficamente la disequazione}
\text{Codages=Codici}
\text{name_solution1=Le croci verdi sono i punti della curva che permettono di risolvere}
\text{name_solution2=I segmenti blu contengono i numeri che sono soluzioni dell'equazione}
\text{name_solution3=Le croci blu sono i limiti dell'insieme delle soluzioni}
\text{Lasolutionest=La soluzione è}
#endif

#if defined TARGET_sensvar3
#endif

#if defined TARGET_sensvargr
#endif

#if defined TARGET_lecttbimage
#endif

#if defined TARGET_affine3
#endif

#if defined TARGET_sensvar2
#endif

