\text{spacebeforecolon=&#32;}

#if defined TARGET_compar2val
#endif

#if defined TARGET_eqgr1
#endif

#if defined TARGET_signgraph
#endif

#if defined TARGET_sensvar1
#endif

#if defined TARGET_lecttbantec
#endif

#if defined TARGET_lectgrantec
#endif

#if defined TARGET_ineqgr
#endif

#if defined TARGET_eqgr2
#endif

#if defined TARGET_exploitabvar
#endif

#if defined TARGET_corrdomain
#endif

#if defined TARGET_racine
#endif

#if defined TARGET_qcmensdef
#endif

#if defined TARGET_quotient1
#endif

#if defined TARGET_ineqgr2courbes
#endif

#if defined TARGET_constrtbvar
#endif

#if defined TARGET_lectvarantec
#endif

#if defined TARGET_quotient2
#endif

#if defined TARGET_extremgr
#endif

#if defined TARGET_extremvar1
#endif

#if defined TARGET_ineqgr2dtes
#endif

#if defined TARGET_lectvarimage
#endif

#if defined TARGET_sensvartb
#endif

#if defined TARGET_quotient3
#endif

#if defined TARGET_ineqgr2
#endif

#if defined TARGET_lectgrimage || defined TARGET_lectgrimage2
\text{lintervalle=l'intervalle}
\text{definiesur=définie sur}
\text{Limagede=L'image de}
\text{estegalea=est égale à}
\text{Paretape=Par étape}

\text{name_imgalt=représentation graphique}
\text{name_statement1=Dans le plan muni d'un repère orthonormé}
\text{name_statement2=on a tracé la courbe représentative d'une fonction}
\text{name_statement3=Déterminez graphiquement l'image de}
\text{name_statement4=par la fonction}
\text{name_solution1a=On trace la droite d'équation}
\text{name_solution1b=en bleue sur le graphique}
\text{name_solution2a=Puis on repère le point d'intersection avec la courbe}
\text{name_solution2b=croix bleue}
\text{name_solution3a=Enfin, on regarde l'ordonnée de ce point}
\text{name_solution3b=Tirets verts}

#endif

#if defined TARGET_sensvar3
#endif

#if defined TARGET_sensvargr
#endif

#if defined TARGET_lectgrantec2
#endif

#if defined TARGET_lecttbimage
#endif

#if defined TARGET_affine3
#endif

#if defined TARGET_sensvar2
#endif

