#if defined TARGET_compar2val
#define TITLE Comparaison et tableau des variations
#endif
#if defined TARGET_eqgr1
#define TITLE Résolution graphique 1: f(x) &#61; k
#endif
#if defined TARGET_signgraph
#define TITLE Signe graphiquement
#endif
#if defined TARGET_sensvar1
#define TITLE Sens de variation 1
#endif
#if defined TARGET_lecttbantec
#define TITLE Lecture d'antécédents par tableau de valeurs
#endif
#if defined TARGET_lectgrantec
#define TITLE Déterminer graphiquement les antécédents
#endif
#if defined TARGET_ineqgr
#define TITLE Résolution graphique f(x) &#139; k
#endif
#if defined TARGET_eqgr2
#define TITLE Résolution graphique 2: f(x) &#61; k
#endif
#if defined TARGET_exploitabvar
#define TITLE Exploiter un tableau de variations; équations
#endif
#if defined TARGET_corrdomain
#define TITLE Correspondance Fonction/ens. de définition
#endif
#if defined TARGET_racine
#define TITLE Ensemble de définition d'une fonction racine
#endif
#if defined TARGET_qcmensdef
#define TITLE QCM Fonction/ens. de définition
#endif
#if defined TARGET_quotient1
#define TITLE Ensemble de définition d'une fonction quotient (1)
#endif
#if defined TARGET_ineqgr2courbes
#define TITLE Résolution graphique 3: f(x)>g(x)
#endif
#if defined TARGET_constrtbvar
#define TITLE Construction du tableau des variations
#endif
#if defined TARGET_lectvarantec
#define TITLE Antécédent par tableau des variations
#endif
#if defined TARGET_quotient2
#define TITLE Ensemble de définition d'une fonction quotient (2)
#endif
#if defined TARGET_extremgr
#define TITLE Fonctions - Extremum graphique
#endif
#if defined TARGET_extremvar1
#define TITLE Extremum et tableau des variations
#endif
#if defined TARGET_ineqgr2dtes
#define TITLE Résolution graphique 2: f(x)>g(x)
#endif
#if defined TARGET_lectvarimage
#define TITLE Image par tableau des variations
#endif
#if defined TARGET_lectgrimage2
#define TITLE Déterminer graphiquement une image 2
#endif
#if defined TARGET_sensvartb
#define TITLE Sens et tableau des variations
#endif
#if defined TARGET_quotient3
#define TITLE Ensemble de définition d'une fonction quotient (3)
#endif
#if defined TARGET_ineqgr2
#define TITLE Résolution graphique 1: f(x)>g(x)
#endif
#if defined TARGET_lectgrimage
#define TITLE Déterminer graphiquement une image
#endif
#if defined TARGET_sensvar3
#define TITLE Sens de variation 3
#endif
#if defined TARGET_sensvargr
#define TITLE Lecture graphique du sens de variation
#endif
#if defined TARGET_lectgrantec2
#define TITLE Déterminer graphiquement les antécédents 2
#endif
#if defined TARGET_lecttbimage
#define TITLE Lecture d'image par tableau de valeurs
#endif
#if defined TARGET_affine3
#define TITLE Ensemble de définition d'une fonction affine
#endif
#if defined TARGET_sensvar2
#define TITLE Sens de variation 2
#endif
