#if defined TARGET_compar2val
#define TITLE_it Comparaison et tableau des variations
#endif
#if defined TARGET_eqgr1
#define TITLE_it Résolution graphique 1: f(x) &#61; k
#endif
#if defined TARGET_signgraph
#define TITLE_it Signe graphiquement
#endif
#if defined TARGET_sensvar1
#define TITLE_it Sens de variation 1
#endif
#if defined TARGET_lecttbantec
#define TITLE_it Lecture d'antécédents par tableau de valeurs
#endif
#if defined TARGET_lectgrantec
#define TITLE_it Determinare graficamente le controimmagini
#endif
#if defined TARGET_ineqgr
#define TITLE_it Résolution graphique f(x) &#139; k
#endif
#if defined TARGET_eqgr2
#define TITLE_it Résolution graphique 2: f(x) &#61; k
#endif
#if defined TARGET_exploitabvar
#define TITLE_it Exploiter un tableau de variations; équations
#endif
#if defined TARGET_corrdomain
#define TITLE_it Correspondance Fonction/ens. de définition
#endif
#if defined TARGET_racine
#define TITLE_it Ensemble de définition d'une fonction racine
#endif
#if defined TARGET_qcmensdef
#define TITLE_it QCM Fonction/ens. de définition
#endif
#if defined TARGET_quotient1
#define TITLE_it Ensemble de définition d'une fonction quotient (1)
#endif
#if defined TARGET_ineqgr2courbes
#define TITLE_it Résolution graphique 3: f(x)>g(x)
#endif
#if defined TARGET_constrtbvar
#define TITLE_it Construction du tableau des variations
#endif
#if defined TARGET_lectvarantec
#define TITLE_it Antécédent par tableau des variations
#endif
#if defined TARGET_quotient2
#define TITLE_it Ensemble de définition d'une fonction quotient (2)
#endif
#if defined TARGET_extremgr
#define TITLE_it Fonctions - Extremum graphique
#endif
#if defined TARGET_extremvar1
#define TITLE_it Extremum et tableau des variations
#endif
#if defined TARGET_ineqgr2dtes
#define TITLE_it Résolution graphique 2: f(x)>g(x)
#endif
#if defined TARGET_lectvarimage
#define TITLE_it Image par tableau des variations
#endif
#if defined TARGET_lectgrimage2
#define TITLE_it Determinare graficamente l'immagine 2
#endif
#if defined TARGET_sensvartb
#define TITLE_it Sens et tableau des variations
#endif
#if defined TARGET_quotient3
#define TITLE_it Ensemble de définition d'une fonction quotient (3)
#endif
#if defined TARGET_ineqgr2
#define TITLE_it Résolution graphique 1: f(x)>g(x)
#endif
#if defined TARGET_lectgrimage
#define TITLE_it Determinare graficamente l'immagine
#endif
#if defined TARGET_sensvar3
#define TITLE_it Sens de variation 3
#endif
#if defined TARGET_sensvargr
#define TITLE_it Lecture graphique du sens de variation
#endif
#if defined TARGET_lectgrantec2
#define TITLE_it Determinare graficamente le controimmagini 2
#endif
#if defined TARGET_lecttbimage
#define TITLE_it Lecture d'image par tableau de valeurs
#endif
#if defined TARGET_affine3
#define TITLE_it Ensemble de définition d'une fonction affine
#endif
#if defined TARGET_sensvar2
#define TITLE_it Sens de variation 2
#endif
