target=sensvar2

#include "header.inc"
#include "lang_titles.inc"

%% This file is generated by preprocessor!
%% Do not edit it by hand.
%% Edit the source file cpp/sensvar.cpp.

\integer{k=randint(1..4)}
\text{monotone=croissante, strictement croissante, décroissante, strictement décroissante, non monotone}
\text{lstrep=\(f(x_1) \le f(x_2)), \(f(x_1) < f(x_2)), \(f(x_1) \ge f(x_2)), \(f(x_1) > f(x_2)), on ne peut pas savoir}


#include "lang.inc"

\statement{
  Soit une fonction \(f) définie sur un intervalle \(I) , telle que
<div class="wimscenter"> pour tous réels \(x_1) et \(x_2) de \(I), tels que \(x_1 < x_2), on a \lstrep[\k]</div>
  Alors \(f) est:
<ul><li>\embed{reply1,1}</li>
<li>\embed{reply1,2}</li>
<li>\embed{reply1,3}</li>
<li>\embed{reply1,4}</li>
<li>\embed{reply1,5}</li>
</ul>
}
\answer{\lstrep[\k]}{\k;\monotone}{type=radio}
