!header
!read Exindex
This module actually contains $exototal exercises on 
geometric applications of definite integrals of one
variable: area, barycenter, arc length, etc.
<p>
There are other modules of exercises on definite integrals:
!href module=U1/analysis/oefdefint OEF definite integral
 for theory and computation of definite integrals, and
!href module=U1/analysis/oefdefintphys OEF physical integral
 for applications on physics.


!read oef/intromenu.phtml
!read related.phtml integrals, area, calculus
!tail

