!header
!read Exindex
!if $lang iswordof it

!! da tradurre in italiano
Ce module regroupe pour l'instant $exototal exercices sur les fonctions:
<ul>
<li> Ensemble de définition </li>
<li> Lecture graphique d'images et d'antécédents</li>
<li> Lecture d'un tableau de valeurs </li>
<li> Lecture d'un tableau de variations </li>
<li> Résolution graphique d'équations</li>
<li> Résolution graphique d'inéquations</li>
</ul>
  

!goto end
!endif
  
Ce module regroupe pour l'instant $exototal exercices sur les fonctions:
<ul>
<li> Ensemble de définition </li>
<li> Lecture graphique d'images et d'antécédents</li>
<li> Lecture d'un tableau de valeurs </li>
<li> Lecture d'un tableau de variations </li>
<li> Résolution graphique d'équations</li>
<li> Résolution graphique d'inéquations</li>
</ul>

:end
!read oef/$module_language/intromenu.phtml
!tail
