!header
!read Exindex

!if $lang iswordof it

<a href="https://wimsedu.info/?page_id=5089" target="_blank">
 <img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" style="float:right;margin-left:0.5em;margin-right:0.2em;"/></a>
Questo modulo raccoglie al momento $exototal esercizi sull'uso e l'interpretazione delle rappresentazioni grafiche delle funzioni.
<div class="wims_credits">La maggior parte degli esercizi sono stati scritti inizialmente da Régine Mangeard</div>
<div class="wims_credits">Aggiornato con il supporto della comunità <a href="https://wimsedu.info/?page_id=5089" target="_blank">MutuWIMS</a></div>

!goto end
!endif

<a href="https://wimsedu.info/?page_id=5089" target="_blank">
 <img src="https://wimsedu.info/wp-content/uploads/2019/06/logo.png" alt="MutuWIMS" width="60" height="61" style="float:right;margin-left:0.5em;margin-right:0.2em;"/></a>
Ce module regroupe pour l'instant $exototal exercices sur l'utilisation et l'interprétation des représentations graphiques des fonctions
au début du lycée.
<div class="wims_credits">La plupart des exercices sont initialement de Régine Mangeard</div>
<div class="wims_credits">Amélioré avec la communauté <a href="https://wimsedu.info/?page_id=5089" target="_blank">MutuWIMS</a></div>

:end
!read oef/intromenu.phtml
!tail
