\text{lang=slib(oef/env lang)}
#if defined TARGET_fracdevinf
\language{fr}

#endif
#if defined TARGET_moninf
\language{fr}

\author{David Doyen}

\email{david.doyen@u-pem.fr}

#endif
#if defined TARGET_polyfactinf3
\language{fr}

\author{David Doyen}

\email{david.doyen@u-pem.fr}

#endif
#if defined TARGET_polydevinf
\language{fr}

\author{David Doyen}

\email{david.doyen@u-pem.fr}

#endif
#if defined TARGET_polyfactinf1
\language{fr}

\author{David Doyen}

\email{david.doyen@u-pem.fr}

#endif
#if defined TARGET_polyfactinf2
\language{fr}

\author{David Doyen}

\email{david.doyen@u-pem.fr}

#endif
#if defined TARGET_fracnondevinf
\language{fr}

#endif
