#if defined TARGET_fracdevinf
#define TITLE Limite en l'infini d'une fraction (développée)
#endif
#if defined TARGET_moninf
#define TITLE Limite en l'infini d'un monôme
#endif
#if defined TARGET_polyfactinf3
#define TITLE Limite en l'infini d'un polynôme (factorisé) 3
#endif
#if defined TARGET_polydevinf
#define TITLE Limite en l'infini d'un polynôme (développé)
#endif
#if defined TARGET_polyfactinf1
#define TITLE Limite en l'infini d'un polynôme (factorisé) 1
#endif
#if defined TARGET_polyfactinf2
#define TITLE Limite en l'infini d'un polynôme (factorisé) 2
#endif
#if defined TARGET_fracnondevinf
#define TITLE Limite en l'infini d'une fraction (non-développée)
#endif
