\text{sbc=&#32}

#if defined TARGET_fracdevinf || defined TARGET_fracnondevinf
\text{name_statement1=Calculer la limite suivante}
\text{\Pourune=Pour une limite égale à}
\text{\danslechamp=dans le champ de réponse}
\text{ecrire=écrire}
\text{Correction=Correction}
\text{en=en}
\text{\Or=Or}
\text{et=et}
\text{est=est}
\text{Dou=D'où}
#endif

#if defined TARGET_fracdevinf
\text{name_feedback1=En mettant en facteur les termes dominants}
\text{name_feedback2=du numérateur et du dénominateur de l'expression, on obtient}
#endif

#if defined TARGET_fracnondevinf
\text{name_feedback1=Le terme dominant du}
\text{name_feedback2=qu'on obtient par un développement partiel}
\text{numerateur=numérateur}
\text{denominateur=dénominateur}
#endif

#if defined TARGET_moninf
#endif

#if defined TARGET_polyfactinf3
#endif

#if defined TARGET_polydevinf
#endif

#if defined TARGET_polyfactinf1
#endif

#if defined TARGET_polyfactinf2
#endif

