\text{sbc=}

#if defined TARGET_fracdevinf || defined TARGET_fracnondevinf
\text{name_statement1=Calcolare il seguente limite}
\text{\Pourune=Per un limite pari a}
\text{\danslechamp=nel campo delle risposte}
\text{ecrire=scrivere}
\text{Correction=Correzione}
\text{en=in}
\text{Or=Ora}
\text{et=e}
\text{est=è}
\text{Dou=Da cui}
#endif

#if defined TARGET_fracdevinf
\text{name_feedback1=Fattorizzando i termini di ordine superiore}
\text{name_feedback2=nel numeratore e denominatore dell'espressione, si ottiene}
#endif

#if  defined TARGET_fracnondevinf
\text{name_feedback1=Il termine di ordine superiore del}
\text{name_feedback2=che otteniamo per espansione parziale}
\text{numerateur=numeratore}
\text{denominateur=denominatore}
#endif

#if defined TARGET_moninf
#endif

#if defined TARGET_polyfactinf3
#endif

#if defined TARGET_polydevinf
#endif

#if defined TARGET_polyfactinf1
#endif

#if defined TARGET_polyfactinf2
#endif

