#if defined TARGET_fracdevinf
#define TITLE_it Limite all'infinito di una frazione (sviluppata)
#endif
#if defined TARGET_moninf
#define TITLE_it Limite en l'infini d'un monôme
#endif
#if defined TARGET_polyfactinf3
#define TITLE_it Limite en l'infini d'un polynôme (factorisé) 3
#endif
#if defined TARGET_polydevinf
#define TITLE_it Limite en l'infini d'un polynôme (développé)
#endif
#if defined TARGET_polyfactinf1
#define TITLE_it Limite en l'infini d'un polynôme (factorisé) 1
#endif
#if defined TARGET_polyfactinf2
#define TITLE_it Limite en l'infini d'un polynôme (factorisé) 2
#endif
#if defined TARGET_fracnondevinf
#define TITLE_it Limite all'infinito di una frazione (non sviluppata)
#endif
