!header
!read Exindex

!if $lang iswordof it

Per gli esercizi di questo modulo si tratta di determinare (esercizi di tipo 1) o di riconoscere (esercizi di tipo 2) la tavola di verità di una proposizione logica.

!goto end
!endif

Dans les exercices de ce module, il s'agit de déterminer (exercices de type 1) ou de reconnaître (exercices de type 2) la table de vérité d'une proposition logique.

:end
!read oef/intromenu.phtml
!tail
