\text{lang=slib(oef/env lang)}
#if defined TARGET_connecteursLN
\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_deduction
\range{-5..5}

\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_implication
\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_incoherence
\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_negationLN
\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_negationMath
\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_reciproque
\range{-5..5}

\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_tautologie
\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_valeursVerite
\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
#if defined TARGET_validite
\author{Véronique Royer}

\email{royer.veronique@orange.fr}

\computeanswer{no}

\format{html}

\precision{10}

#endif
