\text{ou=o}
\text{et=e}
\text{si1=se}
\text{si2=se}
\text{Si1=Se}
\text{Si2=Se}
\text{alors=allora}
\text{oui=sì}
\text{non=no}

#if defined TARGET_connecteursLN
\text{Alist =
c'è uno sciopero degli autobus,
stamattina piove,
fa freddo,
c'è il sole,
sta piovendo,
mangio un sacco di torte,
sono felice,
ascolto Radio Latina,
voglio progredire in matematica,
voglio migliorare il mio inglese,
ho il raffreddore,
lei balla,
suoni la chitarra,
non vuole diventare un ingegnere,
fai schifo in matematica,
siamo tristi,
il lavoro è motivante
}

\text{Blist =
sono in ritardo per la scuola,
prendo il mio ombrello,
mi metto un maglione,
indosso occhiali scuri,
fa freddo,
sto ingrassando,
rido,
io ballo la salsa,
mi esercito con WIMS,
vedrò solo i film in versione originale,
la mia voce è rotta,
lei corre,
tu canti,
lei vuole andare all'estero,
sei forte in francese,
siamo innamorati,
la soddisfazione è totale
}

\text{nonAlist=
non c'è sciopero degli autobus,
stamattina non piove,
non fa freddo,
non c'è il sole,
non sta piovendo,
mangio poche torte,
sono triste,
non ascolto Radio Latina,
non voglio progredire in matematica,
non voglio migliorare il mio inglese,
non ho il raffreddore,
lei non balla,
non suoni la chitarra,
vuole diventare un ingegnere,
sei bravo in matematica,
siamo felici,
il lavoro non è motivante
}

\text{nonBlist=
non sono in ritardo per la scuola,
non prendo il mio ombrello,
non ho indossato un maglione,
non porto occhiali scuri,
è caldo,
non sto ingrassando,
non rido,
non ballo la salsa,
non mi esercito con WIMS,
guardo Lost In Translation in italiano,
parlo normalmente,
lei non corre,
tu non canti,
vuole restare in Italia,
fai schifo in francese,
non siamo innamorati,
la soddisfazione è parziale
}

\text{name_remark=Nota}
\text{name_statement1=Per ciascuna delle seguenti proposizioni, a sinistra, determina la sua struttura logica.}
\text{name_statement2=le proposizioni possono essere solo vere o false... }
\text{name_statement3=(Fare clic sugli elementi corrispondenti a due a due.)}

#endif

#if defined TARGET_deduction
\text{Alist =
c'è uno sciopero degli autobus,
piove al mattino,
fa freddo,
c'è il sole,
mangio un sacco di torte,
sono felice,
io ballo la salsa,
voglio progredire,
voglio migliorare il mio inglese,
ho il raffreddore
}

\text{Blist =
sono in ritardo per la scuola,
prendo il mio ombrello,
mi metto un maglione,
indosso occhiali scuri,
sto ingrassando,
rido,
ascolto solo Radio Latina,
mi esercito con WIMS,
vedo tutti i film in versione originale,
la mia voce è rotta
}

\text{nonAlist=
gli autobus non scioperano,
non piove al mattino,
non è freddo,
non c'è il sole oggi,
ho mangiato poche torte,
sono triste,
non mi piace la salsa,
non voglio progredire,
non voglio migliorare il mio inglese,
non ho il raffreddore
}

\text{nonBlist=
non sono in ritardo per la scuola,
non prendo il mio ombrello,
non ho indossato un maglione,
non porto occhiali scuri,
non sono ingrassato,
non rido,
ho ascoltato Fun Radio,
non mi sono esercitato con WIMS,
Guardo Lost In Translation in italiano,
parlo normalmente
}

\text{name_statement1=Assumiamo che sia vera la seguente implicazione:}
\text{name_statement2=Qualcuno mi incontra e nota che:}
\text{name_statement3=Questa persona deduce che:}
\text{name_statement4=Il suo ragionamento è corretto ?}
\text{name_answer=Ragionameto corretto}
#endif

#if defined TARGET_implication
#endif

#if defined TARGET_incoherence
#endif

#if defined TARGET_negationLN
#endif

#if defined TARGET_negationMath
#endif

#if defined TARGET_reciproque
#endif

#if defined TARGET_tautologie
#endif

#if defined TARGET_valeursVerite
#endif

#if defined TARGET_validite
#endif

