\text{ou=ou}
\text{et=et}
\text{si1=s'}
\text{si2=si}
\text{Si1=S'}
\text{Si2=Si}
\text{alors=alors}
\text{oui=oui}
\text{non=non}

#if defined TARGET_connecteursLN
\text{Alist =
il y a grève de bus,
il pleut ce matin,
il fait froid,
il y a du soleil,
il pleut,
je  mange beaucoup de gâteaux,
je suis joyeux,
j'écoute  Radio Latina,
je veux progresser en maths,
je veux perfectionner mon anglais,
je suis enrhumé(e),
elle danse,
tu joues de la guitare,
elle  ne veut pas devenir ingénieur,
vous êtes nuls en maths,
on est triste,
le travail est motivant
}

\text{Blist =
j'arrive en retard au lycée,
je prends mon parapluie,
je mets un pull,
je porte des lunettes noires,
il fait froid,
je grossis,
je ris,
je  danse  la salsa,
je m'entraîne sous WIMS,
je ne vais voir que des films en VO,
ma voix est cassée,
elle court,
tu chantes,
elle veut partir à l'étranger,
vous êtes forts français,
on est amoureux,
la satisfaction est totale
}

\text{nonAlist=
il n'y a pas grève de bus,
il ne pleut pas ce matin,
il ne fait pas froid,
il n'y a pas de soleil,
il ne pleut pas,
je mange peu de gâteaux,
je suis triste,
je n'écoute pas Radio Latina,
je ne veux pas progresser  en maths,
je ne veux pas améliorer mon anglais,
je ne suis pas enrhumé(e),
elle ne danse pas,
tu ne joues pas de la guitare,
elle  veut devenir ingénieur,
vous êtes forts en maths,
on est joyeux,
le travail n'est pas motivant
}

\text{nonBlist=
je n'arrive pas en retard au lycée,
je ne prends pas mon parapluie,
je n'ai pas mis de pull,
je ne porte pas de lunettes noires,
il fait chaud,
je ne grossis pas,
je ne ris pas,
je ne danse pas la salsa,
je ne m'entraîne pas  sous WIMS,
je regarde Lost In Translation en VF,
je parle normalement,
elle ne court pas,
tu ne chantes pas,
elle veut rester en France,
vous êtes nuls en français,
on n'est pas amoureux,
la satisfaction est partielle
}

\text{name_remark=Remarque}
\text{name_statement1=Pour chacune des propositions  suivantes, à gauche, déterminer sa structure logique.}
\text{name_statement2=les propositions peuvent être vraies ou fausses ...}
\text{name_statement3=(Cliquer sur les élements qui se correspondent deux à deux.)}
#endif


#if defined TARGET_deduction
\text{Alist =
il y a grève de bus,
il pleut le matin,
il fait froid,
il y a du soleil,
je  mange beaucoup de gâteaux,
je suis joyeux,
je danse la salsa,
je veux progresser,
je veux améliorer mon anglais,
je suis enrhumé(e)
}

\text{Blist =
j'arrive en retard au lycée,
je prends mon parapluie,
je mets un pull,
je porte des lunettes noires,
je grossis,
je ris,
je n'écoute que Radio Latina,
je m'entraîne sous WIMS ,
je  vois tous les films en VO,
ma voix est cassée
}

\text{nonAlist=
les bus ne sont pas grève,
il ne pleut pas le matin,
il ne faisait pas froid,
il n'y a pas de soleil aujourd'hui,
j'ai mangé peu de gâteaux,
je suis triste,
je n'aime pas la salsa,
je ne veux pas progresser,
je ne veux pas améliorer mon anglais,
je ne suis pas enrhumé(e)
}

\text{nonBlist=
je n'arrive pas en retard au lycée,
je ne prend pas mon  parapluie,
je n'ai pas mis de pull,
je ne porte pas de lunettes noires,
je n'ai pas grossi,
je ne ris pas,
j'ai écouté Fun Radio,
je ne me suis pas entraîné(e) sous WIMS,
je regarde Lost In Translation en VF,
je parle normalement
}

\text{name_statement1=On suppose que l'implication suivante est vraie :}
\text{name_statement2=Quelqu'un me rencontre et constate que :}
\text{name_statement3=Cette personne en déduit que  :}
\text{name_statement4=Son raisonnement  est-il valide  ?}
\text{name_answer=Raisonnement juste}
#endif

#if defined TARGET_implication
#endif

#if defined TARGET_incoherence
#endif

#if defined TARGET_negationLN
#endif

#if defined TARGET_negationMath
#endif

#if defined TARGET_reciproque
#endif

#if defined TARGET_tautologie
#endif

#if defined TARGET_valeursVerite
#endif

#if defined TARGET_validite
#endif

