#if defined TARGET_connecteursLN
#define TITLE_it Connecteurs booléens
#endif
#if defined TARGET_deduction
#define TITLE_it Déduction logique
#endif
#if defined TARGET_implication
#define TITLE_it Implication en langage naturel
#endif
#if defined TARGET_incoherence
#define TITLE_it Règlement incohérent
#endif
#if defined TARGET_negationLN
#define TITLE_it Négation en langage naturel
#endif
#if defined TARGET_negationMath
#define TITLE_it Négation en mathématiques
#endif
#if defined TARGET_reciproque
#define TITLE_it Réciproque ou Contraposée ?
#endif
#if defined TARGET_tautologie
#define TITLE_it Tautologies
#endif
#if defined TARGET_valeursVerite
#define TITLE_it Valeurs de vérité
#endif
#if defined TARGET_validite
#define TITLE_it Validité d'une proposition
#endif
