\text{lang=slib(oef/env lang)}
#if defined TARGET_pdt2
#endif
#if defined TARGET_tan2
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{yes}

\format{html}

\precision{10000}

#endif
#if defined TARGET_tan4
\language{fr}

\range{-5..5}

\author{Chantal, Causse;Fabien,Sommier}

\email{Chantal.Causse@noos.fr}

\computeanswer{yes}

\format{html}

\precision{10000}

#endif
#if defined TARGET_tan1
\language{fr}

\range{-5..5}

\author{Chantal, Causse; Fabien,Sommier}

\email{Chantal.Causse@noos.fr;fsommier@ac-creteil.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_div1
#endif
#if defined TARGET_form5
#endif
#if defined TARGET_der2
#endif
#if defined TARGET_der3
#endif
#if defined TARGET_tan3
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{yes}

\format{html}

\precision{10000}

#endif
#if defined TARGET_der1
#endif
#if defined TARGET_form1
#endif
#if defined TARGET_pdt
#endif
#if defined TARGET_form6
#endif
#if defined TARGET_tan0
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_form4
#endif
#if defined TARGET_form3
#endif
#if defined TARGET_der6
#endif
#if defined TARGET_der3_b
#endif
#if defined TARGET_pdt1
#endif
#if defined TARGET_form2
#endif
#if defined TARGET_der4
#endif
#if defined TARGET_der5
#endif
