\text{sbc=}
\text{et=e}
\text{est=è}
\text{Si=Se}
\text{si=se}
\text{alors=allora}

#if defined TARGET_pdt2
#endif

#if defined TARGET_tan2
#endif

#if defined TARGET_tan4
#endif

#if defined TARGET_tan1
#endif

#if defined TARGET_div1
#endif

#if defined TARGET_form5
#endif

#if defined TARGET_der2
#endif

#if defined TARGET_der3
\text{name_notation1=Per scrivere}
\text{name_notation2=per esempio, puoi scegliere tra}
\text{Laderivee=La derivata di}
\text{name_statement1=Calcolare la}
\text{name_statement2=derivata della funzione}
\text{name_statement3=definita da}
\text{\estconstante=è una costante}
#endif

#if defined TARGET_tan3
#endif

#if defined TARGET_der1
#endif

#if defined TARGET_form1
#endif

#if defined TARGET_pdt
#endif

#if defined TARGET_form6
#endif

#if defined TARGET_tan0
#endif

#if defined TARGET_form4
#endif

#if defined TARGET_form3
#endif

#if defined TARGET_der6
#endif

#if defined TARGET_der3_b
#endif

#if defined TARGET_pdt1
#endif

#if defined TARGET_form2
#endif

#if defined TARGET_der4
#endif

#if defined TARGET_der5
#endif

