\text{sbc=&#32}
\text{et=et}
\text{est=est}
\text{Si=Si}
\text{si=si}
\text{alors=alors}

#if defined TARGET_pdt2
#endif

#if defined TARGET_tan2
#endif

#if defined TARGET_tan4
#endif

#if defined TARGET_tan1
#endif

#if defined TARGET_div1
#endif

#if defined TARGET_form5
#endif

#if defined TARGET_der2
#endif

#if defined TARGET_der3 || defined TARGET_der4 || defined TARGET_der5 || defined TARGET_der6
\text{name_notation1=Pour écrire}
\text{name_notation2=par exemple, vous avez le choix entre}
\text{Laderivee=La dérivée de}
\text{name_statement1=Calculez la}
\text{name_statement2=dérivée de la fonction}
\text{name_statement3=définie par}
\text{\estconstante=est une constante}
#endif

#if defined TARGET_tan3
#endif

#if defined TARGET_der1
#endif

#if defined TARGET_form1
#endif

#if defined TARGET_pdt
#endif

#if defined TARGET_form6
#endif

#if defined TARGET_tan0
#endif

#if defined TARGET_form4
#endif

#if defined TARGET_form3
#endif

#if defined TARGET_der3_b
#endif

#if defined TARGET_pdt1
#endif

#if defined TARGET_form2
#endif
