#if defined TARGET_pdt2
#define TITLE Produit avec sin ou cos (guidé)
#endif
#if defined TARGET_tan2
#define TITLE Tangente à une courbe polynomiale
#endif
#if defined TARGET_tan4
#define TITLE Tangente à une courbe (avec exp en 0)
#endif
#if defined TARGET_tan1
#define TITLE Tangente à une courbe polynomiale (guidé)
#endif
#if defined TARGET_div1
#define TITLE Dérivée d'un quotient simple
#endif
#if defined TARGET_form5
#define TITLE Formules5 (sqrt,1/x)
#endif
#if defined TARGET_der2
#define TITLE Dérivée de polynome 2
#endif
#if defined TARGET_der3
#define TITLE Dérivée d'exponentielle
#endif
#if defined TARGET_tan3
#define TITLE Tangente à une courbe (avec exp)
#endif
#if defined TARGET_der1
#define TITLE Dérivée de polynome 1
#endif
#if defined TARGET_form1
#define TITLE Formules1 (monomes)
#endif
#if defined TARGET_pdt
#define TITLE Produit avec exponentielle (guidé)
#endif
#if defined TARGET_form6
#define TITLE Formules6 (sin et cos)
#endif
#if defined TARGET_tan0
#define TITLE Tangente et dérivée
#endif
#if defined TARGET_form4
#define TITLE Formules4 (logarithmes)
#endif
#if defined TARGET_form3
#define TITLE Formules3 (exponentielles)
#endif
#if defined TARGET_der6
#define TITLE Dérivée de trinome degré2
#endif
#if defined TARGET_der3_b
#define TITLE Produit avec exponentielle
#endif
#if defined TARGET_pdt1
#define TITLE Produit avec sqrt (guidé)
#endif
#if defined TARGET_form2
#define TITLE Formules2 (polynomes)
#endif
#if defined TARGET_der4
#define TITLE Dérivée de logarithme 1
#endif
#if defined TARGET_der5
#define TITLE Dérivée de logarithme 2
#endif
