\text{name_NECSUF=necessaria e sufficiente}
\text{name_NEC=necessaria (solo)}
\text{name_SUF=sufficiente (solo)}
\text{name_NEC2=necessaria}
\text{name_SUF2=sufficiente}
\text{name_NONNECSUF=né necessaria né sufficiente}
\text{name_IFF=se e solo se}
\text{name_IF=se}
\text{name_ONLYIF=solo se}
\text{name_NONIFONLYIF=né se né solo se}
\text{name_PERNON=probabilmente né necessaria né sufficiente}

#if defined TARGET_subset
\text{name_belongs=appartiene}
\text{name_nbelongs=non appartiene}
#endif

#if defined TARGET_symbol2
\text{name_holds=vale}
\text{name_nholds=non vale}
#endif