\text{name_NECSUF=necessary and sufficient}
\text{name_NEC=necessary (only)}
\text{name_SUF=sufficient (only)}
\text{name_NEC2=necessary (only)}
\text{name_SUF2=sufficient (only)}
\text{name_NONNECSUF=neither necessary nor sufficient}
\text{name_IFF=if and only if}
\text{name_IF=if}
\text{name_ONLYIF=only if}
\text{name_NONIFONLYIF=neither if nor only if}
\text{name_PERNON=perhaps neither necessary nor sufficient}

