#if defined TARGET_3func
#define TITLE Three functions
#endif
#if defined TARGET_3func2
#define TITLE Three functions II
#endif
#if defined TARGET_chsymbol
#define TITLE Chained symbols
#endif
#if defined TARGET_iff
#define TITLE If or only if
#endif
#if defined TARGET_iff2
#define TITLE If or only if II
#endif
#if defined TARGET_iff3
#define TITLE If or only if III
#endif
#if defined TARGET_iff4
#define TITLE If or only if IV
#endif
#if defined TARGET_parity
#define TITLE Parity
#endif
#if defined TARGET_subset
#define TITLE Subset
#endif
#if defined TARGET_symbol
#define TITLE Symbol
#endif
#if defined TARGET_symbol2
#define TITLE Symbol II
#endif
