#if defined TARGET_3func
#define TITLE_it Tre funzioni
#endif
#if defined TARGET_3func2
#define TITLE_it Tre funzioni II
#endif
#if defined TARGET_chsymbol
#define TITLE_it Simboli concatenati
#endif
#if defined TARGET_iff
#define TITLE_it Se o solo se
#endif
#if defined TARGET_iff2
#define TITLE_it Se o solo se II
#endif
#if defined TARGET_iff3
#define TITLE_it Se o solo se III
#endif
#if defined TARGET_iff4
#define TITLE_it Se o solo se IV
#endif
#if defined TARGET_parity
#define TITLE_it Parità
#endif
#if defined TARGET_subset
#define TITLE_it Sottoinsiemi
#endif
#if defined TARGET_symbol
#define TITLE_it Simboli
#endif
#if defined TARGET_symbol2
#define TITLE_it Simboli II
#endif
