\text{lang=slib(oef/env lang)}
#if defined TARGET_pararea2
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_ccrossarea
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{yes}

\format{html}

\precision{10000}

#endif
#if defined TARGET_parcirc
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_lenpolspiral
\language{fr}

\author{Gang XIAO}

\email{xiao@unice.fr}

\format{html}

\precision{3000}

\computeanswer{no}

#endif
#if defined TARGET_arclenexp2d
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{3000}

#endif
#if defined TARGET_lenpolclose
\language{fr}

\author{Gang XIAO}

\email{xiao@unice.fr}

\format{html}

\precision{3000}

\computeanswer{no}

#endif
#if defined TARGET_circdist
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_logarea
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{5000}

#endif
#if defined TARGET_cubicarea
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_lenpolopen
\language{fr}

\author{Gang XIAO}

\email{xiao@unice.fr}

\format{html}

\precision{3000}

\computeanswer{no}

#endif
#if defined TARGET_eclipse
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{600}

#endif
#if defined TARGET_qcrossarea
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{yes}

\format{html}

\precision{10000}

#endif
#if defined TARGET_suprevx
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_pararea
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_reservoir
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{1000}

#endif
#if defined TARGET_arclenparm2d
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{3000}

#endif
#if defined TARGET_volrevx
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_quadarea
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_parabary
\range{-5..5}

\author{Gang XIAO}

\email{xiao@unice.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
