#if defined TARGET_pararea2
#define TITLE Parabolic area II
#endif
#if defined TARGET_ccrossarea
#define TITLE Crossed cubic area
#endif
#if defined TARGET_parcirc
#define TITLE Parabole+circle area
#endif
#if defined TARGET_lenpolspiral
#define TITLE Polar length spiral
#endif
#if defined TARGET_arclenexp2d
#define TITLE Arc length explicit 2D
#endif
#if defined TARGET_lenpolclose
#define TITLE Polar length closed
#endif
#if defined TARGET_circdist
#define TITLE Circular distance
#endif
#if defined TARGET_logarea
#define TITLE Given log area
#endif
#if defined TARGET_cubicarea
#define TITLE Cubic area
#endif
#if defined TARGET_lenpolopen
#define TITLE Polar length open
#endif
#if defined TARGET_eclipse
#define TITLE Eclipse area
#endif
#if defined TARGET_qcrossarea
#define TITLE Crossed quadratic area
#endif
#if defined TARGET_suprevx
#define TITLE Surface of revolution X
#endif
#if defined TARGET_pararea
#define TITLE Parabolic area
#endif
#if defined TARGET_reservoir
#define TITLE Spherical reservoir
#endif
#if defined TARGET_arclenparm2d
#define TITLE Arc length parametric 2D
#endif
#if defined TARGET_volrevx
#define TITLE Volume of revolution X
#endif
#if defined TARGET_quadarea
#define TITLE Given quadratic area *
#endif
#if defined TARGET_parabary
#define TITLE Parabolic barycenter
#endif
