#if defined TARGET_pararea2
#endif

#if defined TARGET_ccrossarea
#endif

#if defined TARGET_parcirc
#endif

#if defined TARGET_lenpolspiral
#endif

#if defined TARGET_arclenexp2d
#endif

#if defined TARGET_lenpolclose
#endif

#if defined TARGET_circdist
#endif

#if defined TARGET_logarea
#endif

#if defined TARGET_cubicarea
#endif

#if defined TARGET_lenpolopen
#endif

#if defined TARGET_eclipse
#endif

#if defined TARGET_qcrossarea
#endif

#if defined TARGET_suprevx
#endif

#if defined TARGET_pararea
\text{name_statement1=Compute the area of the shaded region below, where}
\text{name_statement2=is the curve of the function}
\text{name_statement3=is the line defined by the equation}
\text{name_precision=Please give your result of computation with a precision of at least 5 decimal places.}
\text{\and=and}
\text{\Thearea=The area}
#endif

#if defined TARGET_reservoir
#endif

#if defined TARGET_arclenparm2d
#endif

#if defined TARGET_volrevx
#endif

#if defined TARGET_quadarea
#endif

#if defined TARGET_parabary
#endif

