#if defined TARGET_pararea2
#define TITLE_it Parabolic area II
#endif
#if defined TARGET_ccrossarea
#define TITLE_it Crossed cubic area
#endif
#if defined TARGET_parcirc
#define TITLE_it Parabole+circle area
#endif
#if defined TARGET_lenpolspiral
#define TITLE_it Polar length spiral
#endif
#if defined TARGET_arclenexp2d
#define TITLE_it Arc length explicit 2D
#endif
#if defined TARGET_lenpolclose
#define TITLE_it Polar length closed
#endif
#if defined TARGET_circdist
#define TITLE_it Circular distance
#endif
#if defined TARGET_logarea
#define TITLE_it Given log area
#endif
#if defined TARGET_cubicarea
#define TITLE_it Cubic area
#endif
#if defined TARGET_lenpolopen
#define TITLE_it Polar length open
#endif
#if defined TARGET_eclipse
#define TITLE_it Eclipse area
#endif
#if defined TARGET_qcrossarea
#define TITLE_it Crossed quadratic area
#endif
#if defined TARGET_suprevx
#define TITLE_it Surface of revolution X
#endif
#if defined TARGET_pararea
#define TITLE_it Area parabolica
#endif
#if defined TARGET_reservoir
#define TITLE_it Spherical reservoir
#endif
#if defined TARGET_arclenparm2d
#define TITLE_it Arc length parametric 2D
#endif
#if defined TARGET_volrevx
#define TITLE_it Volume of revolution X
#endif
#if defined TARGET_quadarea
#define TITLE_it Given quadratic area *
#endif
#if defined TARGET_parabary
#define TITLE_it Parabolic barycenter
#endif
