#if defined TARGET_pararea2
#endif

#if defined TARGET_ccrossarea
#endif

#if defined TARGET_parcirc
#endif

#if defined TARGET_lenpolspiral
#endif

#if defined TARGET_arclenexp2d
#endif

#if defined TARGET_lenpolclose
#endif

#if defined TARGET_circdist
#endif

#if defined TARGET_logarea
#endif

#if defined TARGET_cubicarea
#endif

#if defined TARGET_lenpolopen
#endif

#if defined TARGET_eclipse
#endif

#if defined TARGET_qcrossarea
#endif

#if defined TARGET_suprevx
#endif

#if defined TARGET_pararea
\text{name_statement1=Calcola l'area della regione in grigio qui sotto, dove}
\text{name_statement2=è il grafico della funzione}
\text{name_statement3=è la retta definita dall'equazione}
\text{name_precision=Fornire il risultato del calcolo con una precisione di almeno 5 cifre decimali.}
\text{\and=e}
\text{\Thearea=L'area}
#endif

#if defined TARGET_reservoir
#endif

#if defined TARGET_arclenparm2d
#endif

#if defined TARGET_volrevx
#endif

#if defined TARGET_quadarea
#endif

#if defined TARGET_parabary
#endif

