target=lenpolopen

#include "header.inc"
#include "lang_titles.inc"

%% This file is generated by preprocessor!
%% Do not edit it by hand.
%% Edit the source file cpp/lenpol.cpp.

\integer{c1=random(1..5)*random(-1,1)}
\integer{c2=random(1..5)*random(-1,1)}
\integer{c3=random(1..5)*random(-1,1)}
 \real{t1=randint(0..50)/10}
 \real{t2=randint(10*\t1+10..10*\t1+50)/10}
 \real{n1=randint(-50..0)/10}
 \real{n2=randint(10*\t1+10..10*\t1+50)/10}
 \text{data=randomrow(
  t^2+\c1*t+\c2,,\t1,\t2
  t^2+\c1*t+\c2,,\n1,\n2
  \c1*random(sin,cos)(t/random(2,3,4,5,6))-\c2,,\t1,\t2
 )}
text{data=
  \c1*t,,\t1,\t2
}
\function{r=item(1,\data)}
\text{cname=item(2,\data)}
\function{t1=item(3,\data)}
\function{t2=item(4,\data)}
 \real{tr=\t2-(\t1)}
 \real{pt1=\t1-(\tr)}
 \real{pt2=\t2+(\tr)}
\text{mm=slib(function/bounds \r,t,\t1,\t2)}
\text{m1=item(1,\mm)}
\text{m2=item(2,\mm)}
\real{max=1.15*max(abs(\m1),abs(\m2))}
\function{dr=diff(\r,t)}
\real{len=integrate(sqrt((\r)^2+(\dr)^2),t=\t1..\t2)}


#include "lang.inc"

\statement{The following curve \cname is defined by the polar equation
\(r = \r), where \(t) is the polar angle.
 Compute the length of this curve
 for \(t) going from \(\t1) to \(\t2).
<p><center>
\draw{200,200}{
 xrange -\max,\max
 yrange -\max,\max
 fill 0,0,white
 tstep 500
 trange \pt1,\pt2
 arrow 0,0,\max,0,12,grey
 disk 0,0,6,red
 plot skyblue,(\r)*cos(t),(\r)*sin(t)
 trange \t1,\t2
 linewidth 2
 plot blue,(\r)*cos(t),(\r)*sin(t)
}
</center>
}
\answer{The length}{\len}{type=number}
