target=lenpolspiral

#include "header.inc"
#include "lang_titles.inc"

%% This file is generated by preprocessor!
%% Do not edit it by hand.
%% Edit the source file cpp/lenpol.cpp.

\integer{c1=random(1..5)*random(-1,1)}
\integer{c2=random(1..5)*random(-1,1)}
\integer{c3=random(1..5)*random(-1,1)}
 \integer{t1=randint(1..20)}
 \integer{t2=randint(\t1+5..\t1+20)}
 \integer{n1=randint(-20..-1)}
 \integer{n2=randint(\t1+5..\t1+20)}
 \real{s1=randint(2..50)/random(-100,100)}
 \real{s2=randint(2..20)/random(-100,100)}
 \text{data=randomrow(
  \s1*t+\c1,(spiral of Archimedes),\t1,\t2
  \s1*t+\c1,(spiral of Archimedes),\n1,\n2
  exp(\s2*t+\c1),(logarithmic spiral),\n1,\n2
  \c2*exp(\s2*t),(logarithmic spiral),\n1,\n2
  \c1*(t+\c2)^2,(parabolic spiral),\t1,\t2
  \c1*(t+\c2)^2,(parabolic spiral),\n1,\n2
)}
text{data=
  \c1*t,,\t1,\t2
}
\function{r=item(1,\data)}
\text{cname=item(2,\data)}
\function{t1=item(3,\data)}
\function{t2=item(4,\data)}
 \real{tr=\t2-(\t1)}
 \real{pt1=\t1-(\tr)}
 \real{pt2=\t2+(\tr)}
\text{mm=slib(function/bounds \r,t,\t1,\t2)}
\text{m1=item(1,\mm)}
\text{m2=item(2,\mm)}
\real{max=1.15*max(abs(\m1),abs(\m2))}
\function{dr=diff(\r,t)}
\real{len=integrate(sqrt((\r)^2+(\dr)^2),t=\t1..\t2)}


#include "lang.inc"

\statement{The following curve \cname is defined by the polar equation
\(r = \r), where \(t) is the polar angle.
 Compute the length of this curve
 for \(t) going from \(\t1) to \(\t2).
<p><center>
\draw{200,200}{
 xrange -\max,\max
 yrange -\max,\max
 fill 0,0,white
 tstep 500
 trange \pt1,\pt2
 arrow 0,0,\max,0,12,grey
 disk 0,0,6,red
 plot skyblue,(\r)*cos(t),(\r)*sin(t)
 trange \t1,\t2
 linewidth 2
 plot blue,(\r)*cos(t),(\r)*sin(t)
}
</center>
}
\answer{The length}{\len}{type=number}
