!header
!read Exindex
!if $lang iswordof it

I concetti di condizione necessaria e sufficiente sono di importanza
fondamentale nel ragionamento matematico. Per questo motivo
gli esperti in tale tipo di ragionamento, inclusi gli insegnanti di
matematica, spesso sono così abituati al loro utilizzo che non si rendono
conto che i concetti possono apparire difficili e inusuali agli studenti.
<p>
In realtà questi concetti non sono difficili come spesso appaiono ad
alcuni studenti, ed è con la loro pratica che si diventa esperti. Pertanto
raccogliamo qui $exototal esercizi su questi concetti, nella speranza di
rendervi velocemente degli esperti.
</p>
    
!goto end
!endif

The notion of necessary conditions and sufficient conditions is of
fundamental importance in the mathematical reasoning. For this reason,
experts in such reasoning, including math teachers, often get so used to it
that they do not realize how this notion may be difficult and unusual to
students.
<p>
In fact this notion is not so difficult as it often appears to some
students, and it is in practicing that one becomes expert. Therefore we
gather here $exototal training exercises on this notion, in a hope to quickly
make you an expert
</p>

:end
!read oef/intromenu.phtml
!tail
