!header
!read Exindex
Ce module regroupe pour l'instant $exototal exercices sur l'interprétation 
d'une limite en terme d'asymptote, ainsi que les calculs de limites simples 
avec les fonctions polynômes, exponentielles et logarithmes.

<ul class="wims_nopuce">
<li>
Les exercices dont le nom commence par * ne comportent ni fonction exponentielle, 
ni logarithme.
</li><li>La plupart des exercices ne concernent pas les cas d'indétermination 
(croissance comparée) : le but de ces premiers exercices est d'aider à 
la mémorisation des limites des fonctions de base et à l'utilisation 
des opérations sur les limites.
</li><li>
L'exercice détaillé "Limite avec exp(ax+b) et (cx+d) " 
a pour but de séparer les cas avec ou sans indétermination et donne des 
indications pour éventuellement lever l'indétermination.
</li></ul>
!read oef/$module_language/intromenu.phtml
!tail
