#if defined TARGET_etneg1
#define TITLE Deux propositions (et, ou, négation) 1
#endif
#if defined TARGET_etneg2
#define TITLE Deux propositions (et, ou, négation) 2
#endif
#if defined TARGET_impneg1
#define TITLE  Deux propositions (implication, négation) 1
#endif
#if defined TARGET_impneg2
#define TITLE Deux propositions (implication, négation) 2
#endif
#if defined TARGET_etou1
#define TITLE Trois propositions (et, ou) 1
#endif
#if defined TARGET_etou2
#define TITLE Trois propositions (et, ou) 2
#endif
#if defined TARGET_impetou1
#define TITLE Trois propositions (implication, et, ou) 1
#endif
#if defined TARGET_impetou2
#define TITLE Trois propositions (implication, et, ou) 2
#endif
