#if defined TARGET_etneg1
#define TITLE_it Due proposizioni (e, o, negazione) 1
#endif
#if defined TARGET_etneg2
#define TITLE_it Due proposizioni (e, o, negazione) 2
#endif
#if defined TARGET_impneg1
#define TITLE_it Due proposizioni (implicazione, negazione) 1
#endif
#if defined TARGET_impneg2
#define TITLE_it Due proposizioni (implicazione, negazione) 2
#endif
#if defined TARGET_etou1
#define TITLE_it Tre proposizoni (e, o) 1
#endif
#if defined TARGET_etou2
#define TITLE_it Tre proposizoni (e, o) 2
#endif
#if defined TARGET_impetou1
#define TITLE_it Tre proposizoni (implicazione, e, o) 1
#endif
#if defined TARGET_impetou2
#define TITLE_it Tre proposizoni (implicazione, e, o) 2
#endif
