\text{name_and=e}
\text{name_or=o}
\text{name_not=non}

#if defined TARGET_etneg1 || defined TARGET_impneg1
\text{name_statement=Siano P e Q due lettere proposizionali. Determinare la tabella di verità della forma proposizionale}
#endif

#if defined TARGET_etneg2 || defined TARGET_impneg2
\text{name_statement1=Siano P e Q due lettere proposizionali. Si consideri la forma proposizionale T(P,Q), costruita a partire dalle lettere proposizionali P e Q, la cui tabella di verità è indicata di seguito.}
\text{name_statement2=Quale delle seguenti forme proposizionali è logicamente equivalente a T(P,Q) ?}
#endif

#if defined TARGET_etou1 || defined TARGET_impetou1
\text{name_statement=Siano P e Q tre lettere proposizionali. Determinare la tabella di verità della forma proposizionale}
#endif

#if defined TARGET_etou2 || defined TARGET_impetou2
\text{name_statement1=Siano P, Q ed R tre lettere proposizionali. Si consideri la forma proposizionale T(P,Q,R), costruita a partire dalle lettere proposizionali P, Q ed R, la cui tabella di verità è indicata di seguito.}
\text{name_statement2=Quale delle seguenti forme proposizionali è logicamente equivalente a T(P,Q,R) ?}
#endif
