\text{lang=slib(oef/env lang)}
#if defined TARGET_asympt1
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_poly
\author{Chantal, Causse}

\email{chantal.causse@noos.fr}

\format{html}

#endif
#if defined TARGET_aff_exp
\language{fr}

\range{-5..5}

\author{Rémi, Belloeil;Chantal,Causse}d'après un exercice de Véronique Royer

\email{remi.rbelloeil@orange.fr;chantal.causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{100}

#endif
#if defined TARGET_asympt2hv
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_formules2
\language{fr}

\range{-5..5}

\author{Chantal Causse}

\email{Chantal.Causse@ac-lyon.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_formules0
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_simples
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_frac
\author{Chantal, Causse }d'après un exercice de Régine Mangeard

\email{chantal.causse@noos.fr}

\format{html}

#endif
#if defined TARGET_formules02
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_frac2
\author{Chantal, Causse} variante proposée par Rémi Belloeil

\email{chantal.causse@noos.fr}

\format{html}

#endif
#if defined TARGET_formules
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_asympt1hv
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
#if defined TARGET_asympt2
\language{fr}

\range{-5..5}

\author{Chantal, Causse}

\email{Chantal.Causse@noos.fr}

\computeanswer{no}

\format{html}

\precision{10000}

#endif
