#if defined TARGET_asympt1
#define TITLE_it Limite -> asymptote
#endif
#if defined TARGET_poly
#define TITLE_it Polynome en l'infini
#endif
#if defined TARGET_aff_exp
#define TITLE_it Limite avec exp(ax+b) et (cx+d)
#endif
#if defined TARGET_asympt2hv
#define TITLE_it Asymptote (hv) -> limite
#endif
#if defined TARGET_formules2
#define TITLE_it Limites des fonctions de base 2
#endif
#if defined TARGET_formules0
#define TITLE_it *Limites des fonctions de base
#endif
#if defined TARGET_simples
#define TITLE_it Opérations simples sur les limites
#endif
#if defined TARGET_frac
#define TITLE_it Fraction rationnelle en l'infini
#endif
#if defined TARGET_formules02
#define TITLE_it *Limites des fonctions de base 2
#endif
#if defined TARGET_frac2
#define TITLE_it Fraction rationnelle en l'infini (click)
#endif
#if defined TARGET_formules
#define TITLE_it Limites des fonctions de base
#endif
#if defined TARGET_asympt1hv
#define TITLE_it Limite -> asymptote (hv)
#endif
#if defined TARGET_asympt2
#define TITLE_it Asymptote -> limite
#endif
