#if defined TARGET_asympt1
#define TITLE Limite -> asymptote
#endif
#if defined TARGET_poly
#define TITLE Polynome en l'infini
#endif
#if defined TARGET_aff_exp
#define TITLE Limite avec exp(ax+b) et (cx+d)
#endif
#if defined TARGET_asympt2hv
#define TITLE Asymptote (hv) -> limite
#endif
#if defined TARGET_formules2
#define TITLE Limites des fonctions de base 2
#endif
#if defined TARGET_formules0
#define TITLE *Limites des fonctions de base
#endif
#if defined TARGET_simples
#define TITLE Opérations simples sur les limites
#endif
#if defined TARGET_frac
#define TITLE Fraction rationnelle en l'infini
#endif
#if defined TARGET_formules02
#define TITLE *Limites des fonctions de base 2
#endif
#if defined TARGET_frac2
#define TITLE Fraction rationnelle en l'infini (click)
#endif
#if defined TARGET_formules
#define TITLE Limites des fonctions de base
#endif
#if defined TARGET_asympt1hv
#define TITLE Limite -> asymptote (hv)
#endif
#if defined TARGET_asympt2
#define TITLE Asymptote -> limite
#endif
