\text{sbc=}

#if defined TARGET_asympt1
#endif

#if defined TARGET_poly
#endif

#if defined TARGET_aff_exp
#endif

#if defined TARGET_asympt2hv
#endif

#if defined TARGET_formules2
#endif

#if defined TARGET_formules0
#endif

#if defined TARGET_simples
#endif

#if defined TARGET_frac
#endif

#if defined TARGET_formules02
#endif

#if defined TARGET_frac2
#endif

#if defined TARGET_formules
#endif

#if defined TARGET_asympt1hv
#endif

#if defined TARGET_asympt2
\text{name_statement1=Si consideri una funzione}
\text{name_statement2=che ha il grafico}
\text{name_statement3=in un sistema di riferimento ortogonale}
\text{name_statement4=Per mostrare che il grafico}
\text{name_statement5=ammette la retta di equazione}
\text{name_statement6=come asintoto}
\text{name_statement7=bisogna mostrare che}
\text{lalimitede=il limite di}
\text{quand=quando}
\text{tendvers=tende verso}
\text{estegalea=è uguale a}
\text{Remarque=Nota}
\text{Pourecrire=Per scrivere}
\text{pourecrire=per scrivere}
\text{taper=digitare}
\text{ou=o}
\text{en=in}
#endif
