\text{sbc=&#32}

#if defined TARGET_asympt1
#endif

#if defined TARGET_poly
#endif

#if defined TARGET_aff_exp
#endif

#if defined TARGET_asympt2hv
#endif

#if defined TARGET_formules2
#endif

#if defined TARGET_formules0
#endif

#if defined TARGET_simples
#endif

#if defined TARGET_frac
#endif

#if defined TARGET_formules02
#endif

#if defined TARGET_frac2
#endif

#if defined TARGET_formules
#endif

#if defined TARGET_asympt1hv
#endif

#if defined TARGET_asympt2
\text{name_statement1=On considère une fonction}
\text{name_statement2=de courbe représentative}
\text{name_statement3=dans un repère orthogonal}
\text{name_statement4=Pour montrer que la courbe}
\text{name_statement5=admet la droite d'équation}
\text{name_statement6=comme asymptote}
\text{name_statement7=il faut montrer que}
\text{lalimitede=la limite de}
\text{quand=quand}
\text{tendvers=tend vers}
\text{estegalea=est égale à}
\text{Remarque=Remarque}
\text{Pourecrire=Pour écrire}
\text{pourecrire=pour écrire}
\text{taper=taper}
\text{ou=ou}
#endif

