#if defined TARGET_asympt1
#endif

#if defined TARGET_poly
#endif

#if defined TARGET_aff_exp
#endif

#if defined TARGET_asympt2hv
#endif

#if defined TARGET_formules2
#endif

#if defined TARGET_formules0
#endif

#if defined TARGET_simples
#endif

#if defined TARGET_frac
#endif

#if defined TARGET_formules02
#endif

#if defined TARGET_frac2
#endif

#if defined TARGET_formules
#endif

#if defined TARGET_asympt1hv
#endif

#if defined TARGET_asympt2
#endif

